### ISSUE TITLE
Need easy option to save as PNG

### ISSUE THREAD

**Issue by zach-faunalytics** [Faunalytics/faunalytics#7]
can be done using `gt::gtsave`
requires `webshot::install_phantomjs()`

**Comment by jo-faunalytics** [comment]
One thing I realized just now is that of course any formatting that we have to apply manually to the html (e.g., bold or merging cells) won't be captured here. It's not a huge deal, just something to note. 

This might be weird, but I wonder about putting a note in the help file for `table_format` that if it's important those bells and whistles be captured in the report, the user should output to excel/csv format instead and make the table using the table tools in Google Docs?

**Comment by zach-faunalytics** [comment]
Good point - I also want to see if it's possible to output it from R to Excel so it's already made/formatted and you just have to make the HTML edit in Excel for inclusion in the PDF

**Comment by zach-faunalytics** [comment]
For now, you can get most of the formatting working in Excel by saving your table as a .html file (as opposed to .txt) and then opening that .html file in Excel.

**Comment by jo-faunalytics** [comment]
Cool! I had no idea you could open html files with Excel!

**Comment by zach-faunalytics** [comment]
image saving added
