### ISSUE TITLE
Easy-add asterisk (Super optional!)

### ISSUE THREAD

**Issue by jo-faunalytics** [Faunalytics/faunalytics#8]
Feel free to reject if it's more trouble than it seems worth to you, but I just added this code to my current table to indicate with an asterisk when something is significant. Could be cool? Or not? Your call. :)

```
   mutate(Predictor = case_when(`p (FDR)` < .05 ~ paste0(Predictor, "*"),
                                TRUE ~ Predictor))
```

**Comment by jo-faunalytics** [comment]
This was to get around the lack of bold in the fauna tables. Works great as an alternative!

**Comment by zach-faunalytics** [comment]
Added. Not the cleanest, but it works (see `star`, `star_source`, `star_dest`, and `star_alpha`)
